version: "3.8"
services:
  client-react-vite:
    image: client-react-vite
    build:
      context: .
      dockerfile: ./Dockerfile.vite
    init: true
    volumes:
      - .:/usr/src/app # Bind mount the entire app directory
    ports:
      - 5173:5173
    restart: always
    networks:
      - frontend
  client-react-nginx:
    image: client-react-nginx
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    init: true
    networks:
      - frontend
    ports:
      - 80:8080
    restart: unless-stopped

networks:
  frontend:
