version: '3'
services:
  frontend:
    build:
      context: .
      # target: development
    ports:
      - 3001:5173
    stdin_open: true
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    networks:
      - frontend-network

networks:
  frontend-network:
